# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'myapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/DynamicLinks', '~> 5.11.0'
  pod 'GoogleAppMeasurement', '5.3'

  # Pods for myapp

  target 'myapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myapp-tvOS
end
